// <auto-generated />
using System;
using Life.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Life.Data.Migrations
{
    [DbContext(typeof(LifeDbContext))]
    [Migration("20191007074519_Splits the set into two seperate types")]
    partial class Splitsthesetintotwoseperatetypes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Life.Core.Domain.Exercise.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ExerciseInfoId");

                    b.Property<int?>("WorkoutId");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseInfoId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("Life.Core.Domain.Exercise.ExerciseInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Description");

                    b.Property<int>("ExerciseType");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("ExercisesInfo");
                });

            modelBuilder.Entity("Life.Core.Domain.Exercise.Set", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int?>("ExerciseId");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("Set");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Set");
                });

            modelBuilder.Entity("Life.Core.Domain.Exercise.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("Life.Core.Domain.Exercise.DurationSet", b =>
                {
                    b.HasBaseType("Life.Core.Domain.Exercise.Set");

                    b.HasDiscriminator().HasValue("DurationSet");
                });

            modelBuilder.Entity("Life.Core.Domain.Exercise.WeightSet", b =>
                {
                    b.HasBaseType("Life.Core.Domain.Exercise.Set");

                    b.Property<int>("Reps");

                    b.Property<int>("Weight");

                    b.HasDiscriminator().HasValue("WeightSet");
                });

            modelBuilder.Entity("Life.Core.Domain.Exercise.Exercise", b =>
                {
                    b.HasOne("Life.Core.Domain.Exercise.ExerciseInfo", "ExerciseInfo")
                        .WithMany()
                        .HasForeignKey("ExerciseInfoId");

                    b.HasOne("Life.Core.Domain.Exercise.Workout")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutId");
                });

            modelBuilder.Entity("Life.Core.Domain.Exercise.Set", b =>
                {
                    b.HasOne("Life.Core.Domain.Exercise.Exercise")
                        .WithMany("Sets")
                        .HasForeignKey("ExerciseId");
                });
#pragma warning restore 612, 618
        }
    }
}
